from django.urls import path, include
from .views import (
    UserList,
    UserInfo,
    CreateBlogPost,
    UpdateBlogPost,
    DeleteBlogPost,
    LikeBlogPost,
    ListBlogPosts,
    SearchBlogPost,
    ListUserBlogPosts,
    signup,
    Home,
    # CreateTravelInfo,
    UpdateTravelInfo,
    CreateComment,
    UpdateComment,
    DeleteComment,
    DeleteTravelInfo,
    DeleteLikePost,
    ListPostComments,
    ListUserComments,
    ListUserLikes,
    AddBlogTag,
    AddUserTag, 
    FacebookSignup, 
    FacebookLogin,
    DeleteUserTag, 
    DeleteBlogTag,
    Login)

urlpatterns = [
    # Path for user authentication using django built-in auth app
    path('accounts/', include('django.contrib.auth.urls')),
    # Path for users
    path('', Home.as_view(), name="home_urlpattern"),
    path('signup', signup, name="user_signup_urlpattern"),
    path('loggedin', Login.as_view(), name="user_login_urlpattern"),
    # url(r'^login/$','django.contrib.auth.views.login', {'template_name': '/login.html'}),
    path('facebook_signup', FacebookSignup.as_view(), name="user_facebook_signup_urlpattern"),
    path('facebook_login', FacebookLogin.as_view(), name="user_facebook_login_urlpattern"),
    path('users/list', UserList.as_view(), name="user_list_urlpattern"),
    path('users/<int:pk>', UserInfo.as_view(), name="user_info_urlpattern"),
    # Path for blogpost
    path('blogpost/create', CreateBlogPost.as_view(),
         name="create_blogpost_urlpattern"),
    path('blogpost/list/', ListBlogPosts.as_view(),
         name="list_blogpost_urlpattern"),
    path('blogpost/list/<int:user_id>', ListUserBlogPosts.as_view(),
         name="user_list_blogpost_urlpattern"),
    path('blogpost/update/<int:post_id>', UpdateBlogPost.as_view(),
         name="update_blogpost_urlpattern"),
    path('blogpost/delete/<int:post_id>', DeleteBlogPost.as_view(),
         name="delete_blogpost_urlpattern"),
    path('blogpost/search/<str:search_keyword>',
         SearchBlogPost.as_view(), name="search_blogpost_urlpattern"),

    path('blogpost/deletelikepost', DeleteLikePost.as_view(),
         name="delete_like_blogpost_urlpattern"),
    path('blogpost/likepost', LikeBlogPost.as_view(),
         name="like_blogpost_urlpattern"),

    path('blogpost/<int:postid>/comments', ListPostComments.as_view(),
         name="list_post_comments_urlpattern"),
    path('blogpost/<int:user_id>/likes', ListUserLikes.as_view(),
         name="list_user_like_urlpattern"),
    path('comment/list/<int:user_id>', ListUserComments.as_view(),
         name="list_user_comments_urlpattern"),

    # path('travelinfo/create/<int:user_id>', CreateTravelInfo.as_view(),
    #      name="create_travelinfo_urlpattern"),
    path('travelinfo/update/<int:user_id>', UpdateTravelInfo.as_view(),
         name="update_travelinfo_urlpattern"),
    path('travelinfo/delete/<int:user_id>', DeleteTravelInfo.as_view(),
         name="delete_travelinfo_urlpattern"),
    path('comment/create/', CreateComment.as_view(),
         name="create_comment_urlpattern"),
    path('comment/update/<int:comment_id>', UpdateComment.as_view(),
         name="update_comment_urlpattern"),
    path('comment/delete/<int:comment_id>', DeleteComment.as_view(),
         name="delete_comment_urlpattern"),

    path('blogpost/<int:postid>/addtag', AddBlogTag.as_view(),
         name='add_blogtag_urlpattern'),
    path('blogpost/<int:postid>/deletetag', DeleteBlogTag.as_view(),
         name='add_blogtag_urlpattern'),
    path('users/<int:userid>/addtag', AddUserTag.as_view(),
         name='add_usertag_urlpattern'),
    path('users/<int:userid>/deletetag', DeleteUserTag.as_view(),
         name='add_usertag_urlpattern'),
]
